### ISSUE TITLE
global PR template doesn't correspond to some projects structure

### ISSUE THREAD

**Issue by and800** [aio-libs/.github#1]
There's no library except aiohttp which does track all contributor names and pending changes

**Comment by kxepal** [comment]
It's good idea to fix that.

**Comment by webknjaz** [comment]
This template is only a fallback. All projects should have their specific templates anyway.

**Comment by asvetlov** [comment]
aiohttp has own templates.
If somebody would propose a PR here to change the default template -- you are welcome!

**Comment by webknjaz** [comment]
I think that it's useful to have that in the fallback template. It shouldn't be an excuse for not having specialized per-repo templates.

**Comment by and800** [comment]
@webknjaz I mean, the given fallback would be unusable in the most of cases. If some repo doesn't have its specific templates, it is likely that it either doesn't have `CONTRIBUTORS.txt` and `CHANGES` directory, also not every repo has the documentation.

**Comment by asvetlov** [comment]
Adding a template to every small repo is a maintenance burden.
The default should exist and should be reasonably good, isn't it?
Otherwise, the PR for defaults should show a text like "Please fix default templates for the project" which doesn't look friendly :)
`CONTRIBUTORS` and `CHANGES` sections can be dropped here if they mean nothing for most aio-libs projects. Why not?

**Comment by webknjaz** [comment]
Okay, go ahead
